"""Example plugin — a working skeleton for third-party plugin authors.

This plugin doesn't fetch anything real. It yields a small in-memory
sample of items each time it runs, so you can verify that manifest
declaration, registration, and the fetch loop all work together
before you plug in a real API.

Copy this directory to a new name in `plugins/<your_plugin_name>/`,
rename the plugin_id + display_name, and start integrating.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Iterator

from pipeline.models import RawItem
from sources.base import (
    FetchStats,
    FieldSpec,
    Source,
    SourceCursor,
    SourceManifest,
)


# ---------------------------------------------------------------------------
# MANIFEST — describes this plugin to the webui and the pipeline.
# ---------------------------------------------------------------------------

MANIFEST = SourceManifest(
    plugin_id="example",
    display_name="Example Plugin",
    version="0.1.0",
    docs_url="https://github.com/YOUR-NAME/YOUR-REPO",
    help=(
        "Example plugin — yields fake items. Copy plugins/example/ to a "
        "new directory in plugins/ and edit plugin.py to write your own."
    ),
    connection_fields=[
        # No auth needed for this example — real plugins usually have keys here.
        # FieldSpec(name="EXAMPLE_API_KEY", label="API key", type="secret",
        #           required=True, help="Get one at ..."),
    ],
    stream_fields=[
        FieldSpec(
            name="name",
            label="Stream name",
            type="text",
            required=True,
            placeholder="my-stream",
            help="Internal label for cursor / dedup.",
        ),
        FieldSpec(
            name="topic",
            label="Topic",
            type="text",
            required=True,
            placeholder="python",
            help="The topic to fetch. Example plugin ignores this — real plugins would use it.",
        ),
        FieldSpec(
            name="limit",
            label="Max items per fetch",
            type="number",
            default=5,
            help="How many fake items to yield. Real plugins would paginate against an API.",
        ),
    ],
    identifier_field="topic",
    credibility_weight_default=0.5,   # example plugin isn't a real signal
)


# ---------------------------------------------------------------------------
# The Source subclass — runtime behavior.
# ---------------------------------------------------------------------------


class ExampleSource(Source):
    name = "example"

    def __init__(self) -> None:
        # Real plugins init HTTP clients, DB connections, etc. here.
        pass

    def fetch_since(
        self,
        cursor: SourceCursor,
        config: dict[str, Any],
        stats: FetchStats,
    ) -> Iterator[RawItem]:
        """Yield fake items. Real plugins would call an API here."""
        topic = config.get("topic", "unknown")
        limit = int(config.get("limit", 5))
        stream_name = config.get("name", "example-default")
        floor = cursor.cursor_ts or 0.0

        now = datetime.now(timezone.utc)
        newest_seen = floor

        for i in range(limit):
            # Fake timestamp: staggered a few seconds apart, all in the last hour
            fake_ts = now.timestamp() - (i * 60)
            if fake_ts <= floor:
                continue   # already fetched last run

            fake_id = f"example-{topic}-{int(fake_ts)}"
            yield RawItem(
                source="example",
                source_display_name=MANIFEST.display_name,
                external_id=fake_id,
                url=f"https://example.com/{topic}/{fake_id}",
                parent_external_id=None,
                author="example-user",
                created_at=datetime.fromtimestamp(fake_ts, tz=timezone.utc),
                title=f"Example post {i+1} about {topic}",
                body=(
                    f"This is a fake post generated by the example plugin. "
                    f"Stream: {stream_name}. Topic: {topic}. Index: {i+1}. "
                    f"Replace ExampleSource.fetch_since() with a real API call."
                ),
                engagement={"score": 10 - i, "comments": 3 - (i % 3)},
                raw={"topic": topic},
            )

            if fake_ts > newest_seen:
                newest_seen = fake_ts

        if newest_seen > floor:
            cursor.cursor_ts = newest_seen
